### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by dkit150750** [Qvant-lab/qui-max#157]
Здравствуйте. Подскажите, пожалуйста, может я что-то делаю не так. Не могу собрать проект. 
Использую стартовый шаблон vitesse,
https://github.com/antfu/vitesse

включающий в себя плагин vite-ssg
При сборке выдает ошибку.
ReferenceError: HTMLElement is not defined
![Снимок экрана (146)](https://user-images.githubusercontent.com/74464479/132499263-49036787-fb7b-40fc-8c8f-bb5b957526c5.png)

**Comment by ViZhe** [comment]
Приветствую, без примера для воспроизведения сложно сказать наверняка в чем может быть причина, но в целом выглядит словно типы для dom не подключены в tsconfig.json файле

**Comment by ViZhe** [comment]
хотя выглядит что это проблема совместимости библиотеки с SSR, я посмотрю что можно сделать с этим

<img width="1280" alt="изображение" src="https://user-images.githubusercontent.com/8091902/132511651-e21a490a-8f8e-44b9-8159-16302e5b81bc.png">

**Comment by dkit150750** [comment]
https://github.com/dkit150750/timetable
вот пример

**Comment by ViZhe** [comment]
да, это проблема текущей библиотеки, постараемся добавить поддержку SSR в одном из ближайших релизов

**Comment by ViZhe** [comment]
@dkit150750 я подготовил ПР, хотя толком не успел протестировать, но указанный выше проект начал собираться, следующий релиз я думаю стоит ожидать в пределах 2 недель.
Вы можете спулить репу, переключиться на ветку `ssr` и собрать проект `yarn && yarn build`, затем заменить полученной dist директорией свою локальную директорию в node_modules, это должно снять текущий блокер и позволит разрабатывать, а заодно и тестировать правки, так что если столкнётесь с проблемами при серверном рендеринге компонентов библиотеки, дайте знать :)

Так же отмечу что применительно к `timetable` стоит так же
1) удалить в вашем проекте `import '@qvant/qui-max/styles';` из `/src/layouts/admin.vue#L11`, `/src/layouts/adminMain.vue#L11` и `/src/layouts/login.vue#L20`
2) добавить строчку `@import '@qvant/qui-max/styles';` в `src/assets/styles/qui-main.css#L1` , ну или где это более походит проекту

https://github.com/Qvant-lab/qui-max/pull/159

**Comment by dkit150750** [comment]
Не знаю с чем связано. Некорректно работает Vue.js devtools. даже когда на странице нет компонентов библиотеки.
![Снимок экрана (156)](https://user-images.githubusercontent.com/74464479/132634321-bcba1964-0715-4106-ac59-5011faa07e4d.png)

**Comment by ViZhe** [comment]
@dkit150750  QNotification (а так же QProgressIndicatior) маунтится как отдельное Vue приложение при подключении Qui для того, чтобы можно было вызывать нотифаи из кода любого компонента, соответственно в devtools достаточно переключить инспектируемый Vue инстанс как на скриншоте ниже

<img width="443" alt="изображение" src="https://user-images.githubusercontent.com/8091902/132642472-d9a2b845-f353-4fb4-9be4-0f0d5da5d06b.png">

**Comment by dkit150750** [comment]
Спасибо👍
