### ISSUE TITLE
Use Stylus instead of SCSS/Sass

### ISSUE THREAD

**Issue by InfoLibre** [Qvant-lab/qui-max#192]
Stylus syntax is more powerful than Sass or Less.
https://github.com/stylus/stylus

**Comment by Tim152** [comment]
thank you, but it's as huge change, scss covers all our features for now

**Comment by InfoLibre** [comment]
It's interesting to have a release for Sass, Stylus ans Less, like Fomantic-UI.

https://github.com/fomantic/Fomantic-UI-CSS

https://github.com/fomantic/Fomantic-UI-LESS

https://github.com/fomantic/Fomantic-UI-SASS

https://github.com/fomantic/Fomantic-UI/issues/2152

Developers don't have to learn a new CSS preprocessor syntax for their project.

https://github.com/mojotech/sass2stylus
