### ISSUE TITLE
Width property in QTabPane not working correctly

### ISSUE THREAD

**Issue by mike1694** [Qvant-lab/qui-max#240]
template:
<img width="246" alt="Снимок экрана 2022-02-18 в 09 59 38" src="https://user-images.githubusercontent.com/38811225/154909017-d07c3435-4acb-48ec-9360-c0ed88579132.png">
result:
<img width="203" alt="Снимок экрана 2022-02-18 в 10 00 40" src="https://user-images.githubusercontent.com/38811225/154909032-333eaf0c-7f34-4804-99ff-f989c90de62d.png">

template:
<img width="242" alt="Снимок экрана 2022-02-18 в 10 01 22" src="https://user-images.githubusercontent.com/38811225/154909080-217cf487-f9eb-4e83-b56e-b623d5b17432.png">
result: 
<img width="219" alt="Снимок экрана 2022-02-18 в 10 01 13" src="https://user-images.githubusercontent.com/38811225/154909116-c8263fbd-0ba8-40a4-847e-47d6a78fc5c9.png">

**Comment by Tim152** [comment]
Hi, @mike1694, check v0.9.1 out
