### ISSUE TITLE
Hello, the design is beautiful, can I add Chinese support? And which branch should I merge into?

### ISSUE THREAD

**Issue by ckvv** [Qvant-lab/qui-max#269]

**Comment by Tim152** [comment]
Hello, @ckvv, thank you!
That's a great idea, you should create a new Chinese locale here https://github.com/Qvant-lab/qui-max/tree/main/src/qComponents/constants/locales, you'll find the config in `en.ts`, add a new file with translation, change a few imports (or we can help) and create a PR to `main` branch
