### ISSUE TITLE
Выбранное значение не рендерится после получения опций

### ISSUE THREAD

**Issue by mike1694** [Qvant-lab/qui-max#300]
Кейс: у меня есть значение и зная его я получаю опции с API чуть позже.

Код:
<img width="551" alt="Снимок экрана 2022-06-02 в 11 41 25" src="https://user-images.githubusercontent.com/38811225/171591411-eb224cdb-6ca5-4d9c-86e9-0568e694cf5c.png">

Селект, нет значения:
<img width="771" alt="Снимок экрана 2022-06-02 в 11 30 15" src="https://user-images.githubusercontent.com/38811225/171589658-b582c78f-4ff3-47aa-b695-40ade6a0220e.png">

Выпадающий список, видно, что значение выбрано:
<img width="774" alt="Снимок экрана 2022-06-02 в 11 30 10" src="https://user-images.githubusercontent.com/38811225/171589737-1e873247-7117-479d-90c3-0f59e98b380b.png">

**Comment by Tim152** [comment]
@mike1694 Привет! Спасибо, поправим в ближайшем релизе
