### ISSUE TITLE
Не хватает класса q-select__disabled в QSelect

### ISSUE THREAD

**Issue by mike1694** [Qvant-lab/qui-max#312]
Привет. Добавьте, пожалуйста, класс q-select__disabled в QSelect чтобы была возможность стилизовать QTag.
<img width="341" alt="Снимок экрана 2022-06-27 в 10 34 09" src="https://user-images.githubusercontent.com/38811225/175888092-1df77652-11f6-410d-a01a-6ca27ab5cdf1.png">

**Comment by mike1694** [comment]
<img width="572" alt="Снимок экрана 2022-06-27 в 10 54 27" src="https://user-images.githubusercontent.com/38811225/175888918-0a74e10d-f333-4dff-98cc-82e67bf15cb4.png">

**Comment by raha-frontend** [comment]
сделал пулреквест 
https://github.com/Qvant-lab/qui-max/pull/316
